### ISSUE TITLE
show active filter in Flatsome theme

### ISSUE THREAD

**Issue by SemT** [FacetWP/facetwp-flatsome#1]
the flatsome integration doesn't hook into the Flatsome active filters. 

in the following image you can see the Active Filters on attributes. FacetWP doesn't use these, but rather its own shortcode. But it's much nicer to hook into the Flatsome layout for active filters
![image](https://user-images.githubusercontent.com/621729/43397690-00a3587a-9406-11e8-9197-98ed5dedcaff.png)

**Comment by mgibbs189** [comment]
@SemT That change would need to be implemented by the Flatsome theme itself.

We do have a "User selections" shortcode: `[facetwp selections="true"]` meaning that you could also manually put this into your theme (not sure which template file to edit though).
